inhibit_all_warnings! # This will disable all the warnings for all pods!

target "TestableSegueDemo" do
# Main application target is not used.
end

target "HSPTestableSegueDemoTests", :exclusive => true do
  pod "OCMockito"
end
